mozilla/mozfest-event-app

js/schedule.js
This fixes https://github.com/mozilla/mozfest-schedule-app/issues/15
=> search box also matches pathway and space names

css/schedule.css, index.html, js/schedule.js, spaces.json
this wraps up https://github.com/mozilla/mozfest-schedule-app/issues/18, build Spaces views
=> Wraps up Spaces views

.travis.yml
A 15 minute cronjob will make this annoying so moving it off our main channel.
=> Change notification channel

index.html
fixes https://github.com/mozilla/mozfest-schedule-app/issues/42
=> Html tweaks 42

css/schedule.css
Removed a dot on end of property
=> Remove dot on property

js/schedule.js
in case the "remove whitespace on empty line" changes are not okay, I can strip them and re-push
=> "No matching results" should be an a new line (fixes #38)

js/schedule.js
fixes https://github.com/mozilla/mozfest-schedule-app/issues/37
=> hide "open" blocks on Favorites page

spaces.json
As per https://github.com/mozilla/mozfest-schedule-app/issues/53
=> Update 'Mozilla Learning Networks' text

index.html, js/schedule.js
=> Fixes #24 - shows facilitator meta in detail view

index.html
... it reads better this way i think
=> adding a comma before description of a facilitator

css/schedule.css, js/schedule.js
=> show "loading..." text if sessions.json is taking a few seconds

js/schedule.js
fixes the issue where on first load the schedule block as the wrong height
=> callback based block sizing

pathways.json
copy taken from https://public.etherpad-mozilla.org/p/festival-pathways
=> Fixes #87 - added pathway description

index.html
As per https://github.com/mozilla/mozfest-schedule-app/issues/82
Creating the PR so will only need to be merged
=> Deletion of Draft from tittle

index.html, pathways.json, sessions.json
We might not want to be showing as a draft schedule anymore.
=> No longer draft.

index.html
Medium sessions starting at 5:00pm (not 5:30pm)
=> changed time for main stage event time block

css/schedule.css, index.html, js/schedule.js, sessions.json
=> Converted indentation from 4-space to 2

index.html, js/schedule.js
=> Removed hardcoded schedule block containers from index.html

index.html
Fixes #157 
Most of it has been taken care of in previous commits. This PR just adds some notes to the custom config options.
=> Accept event-specific strings via config

js/schedule.js
=> Unfavourite sessions bug

css/schedule.css, sample-index.html
=> Added link to session etherpad

css/schedule.css, demo/index.html
=> Abstracted 'etherpad slug' into 'notes url'

js/schedule.js
=> Add preventDefault to nav links handlers

js/schedule.js
=> Fixed wrong timeblocks order

js/schedule.js
=> Sorted search results chronologically

css/schedule.css, js/schedule.js
=> Removed 'show description' toggle from Search

js/schedule.js
=> Turned Search help text into placeholder text

js/schedule.js
=> Hide thumbnail cards until user starts typing

css/schedule.css, demo/index.html, js/schedule.js
=> Clicking on logo brings you back to landing page

js/schedule.js
=> Removed show/hide toggle

css/mofo-bootstrap.css, css/schedule.css, demo/style.css
=> Cleaned up CSS & made it mobile first

css/schedule.css, js/schedule.js
=> Removed Space/Pathway page title

css/schedule.css, js/schedule.js
=> Show date picker only on a few specific views

css/schedule.css, demo/style.css, js/schedule.js
=> Session cards should be collapsed by default

css/schedule.css, demo/iron-chef-sessions.json, demo/style.css, js/schedule.js
=> Fixed back button behaviour bug

js/schedule.js
=> Updated 'no search result' text

css/schedule.css
=> Changed text alignment in timeblock divider

css/schedule.css, demo/index.html, demo/style.css, js/schedule.js
=> Main nav tweaks

css/schedule.css
=> Fixed Fira not loading problem on mobile

demo/index.html, js/schedule.js
=> Fixed schedule link and logo link bug on mobile

js/schedule.js
=> Fixed search mode cancel button bug

css/schedule.css, demo/index.html, demo/style.css, js/schedule.js
=> Search screen tweaks

css/schedule.css, css/style.css, index.html, js/schedule.js, sessions.json
=> everyone sessions

index.html, sessions.json
=> Display session end time

css/schedule.css, css/style.css, index.html, js/schedule.js, sessions.json, spaces.json
=> New design for spaces screens

index.html
=> Removed pathway info from session card

index.html, sessions.json
=> Sanitized session data

js/schedule.js
=> Turned marked's sanitize option to true

css/style.css
=> Updated text link colour to pink

index.html, spaces.json
=> Updated Space descriptions

css/schedule.css, index.html, js/schedule.js, pathways.json, sessions.json
=> Implemented new design for pathway pages

js/schedule.js
=> Fixed broken day tabs

docs/JSON_FORMAT.md, index.html, js/schedule.js, sessions.json
=> Styled facilitator info + code cleanup + doc updates

css/style.css
=> Colour changes for notes button

css/schedule.css, css/style.css, js/schedule.js, sessions.json
=> Added full header back to detail view

index.html, js/schedule.js
=> Fixed detail view space and pathway links bug

css/schedule.css, index.html
=> Header styling tweaks

css/schedule.css, docs/JSON_FORMAT.md, index.html, sessions.json
=> Support non EN sessions

js/schedule.js
=> Removed back button from individual space/pathway pages

css/schedule.css, index.html, js/schedule.js, pathways.json, sessions.json
Added "might not be finalized" pathway info
=> Pathways list

css/schedule.css, css/style.css, js/schedule.js, spaces.json
=> Adjusted space icon sizing, space/pathway screens styling

css/schedule.css
=> Updated lang icon

css/schedule.css, docs/JSON_FORMAT.md, index.html, sessions.json
Fixes #371
- started displaying WIP schedule
- renamed 'everyone' session in code to 'programmatic'
=> Started displaying WIP schedule

js/schedule.js, spaces.json
=> Updated D&D description

index.html
=> Removed extra gap after facilitators info

.travis.yml
https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
=> So that Travis supports merges to non-default branches

docs/JSON_FORMAT.md, index.html, js/schedule.js, sessions.json
=> Reads and displays new pathways format and names

sessions.json, spaces.json
=> Tweaked D&D name + updated sessions.json

sessions.json
=> Updated sunday first block and sessions.json

index.html
=> Show facilitator icon when needed

css/style.css, scss/_variables.scss, scss/style.scss
=> design tweaks

index.html, js/schedule.js
=> Lands on today's day tab if the date matches

js/schedule.js
=> Made 'additional language' meta searchable

index.html, js/ga-with-do-not-track-check.js
=> Updated GA UA and made it check for browser's DNT preferenece

js/schedule.js
=> Added GA events

README.md, index.html, js/schedule.js
=> Removed console.log lines and 'WIP' notes from codebase

js/schedule.js
=> GA and Do Not Track bug

js/schedule.js
=> Fixing GA and DNT bug

sessions.json
leading and trailing whitespaces have been stripped from string based session meta
=> Updated sessions.json

css/style.css, js/schedule.js, scss/style.scss
=> Slider animation improvement

css/style.css, index.html, js/schedule.js, scss/style.scss
=> Removed session-ghost related code

js/schedule.js
=> Made the first timeblock on Friday tab expanded by default

css/style.css, js/schedule.js, scss/style.scss
=> Shows loading icon while loading sessions/spaces/pathways data into app

js/schedule.js
=> Bug fixes and code improvement for timeblock's expand/collapse states

index.html
=> Display facilitator info on detail view and search view

js/schedule.js
=> Preserve toggle and scroll states
